### ISSUE TITLE
Add Support for Journal Pages introduced in Foundry V10

### ISSUE THREAD

**Issue by icristianhrimiuc** [BeneosBattlemaps/Beneos-Point-Of-Interest-Teleporter#3]
There is a bug related to journal subpages described and fixed by ByronThompson in this [PR](https://github.com/zeel01/poi-teleport/pull/16) on the original GIT repository

**Comment by LeRatierBretonnien** [comment]
PR will be backported into the new repo, and will be available in next release after testing.
Thanks for the report !
